[server]
# If you want to serve Grafana from a subpath (for example if you are hosting Grafana under grafana.mydomain.com/grafana), 
# then set this to the subpath. Make sure you include the trailing forward slash (/).
root_url = http://localhost:3000/grafana/
serve_from_sub_path = true
