  name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitLab Container Registry
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login ${{ secrets.CI_REGISTRY }} -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.CI_REGISTRY }}/terraformazure/myimage:latest .
          docker push ${{ secrets.CI_REGISTRY }}/terraformazure/myimage:latest

