FROM denvazh/gatling:latest

# Exponer el puerto para el acceso a los resultados de Gatling
EXPOSE 8080

# Copiar los archivos de configuración de Gatling
COPY gatling.conf /opt/gatling/conf/gatling.conf

