FROM node:14-alpine

# Crear directorio de trabajo
WORKDIR /app

# Copiar solo el package.json
COPY package.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto
EXPOSE 1337

# Comando para iniciar la aplicación
CMD ["npm", "start"]

