# Dockerfile.lint
FROM python:3.9

# Directorio de trabajo
WORKDIR /app

# Copia el código del proyecto al contenedor
COPY ./app /app

# Instala pylint y flake8
RUN pip install pylint flake8

# Comando por defecto para ejecutar los linters
CMD ["sh", "-c", "pylint . && flake8 .", ">pylint-report.txt"]

