version: '3.8'

services:
  app1:
    build:
      context: ./app
    environment:
      - FLASK_APP=app.py
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - monitoring_net
    restart: always
    container_name: app1

  app2:
    build:
      context: ./app
    environment:
      - FLASK_APP=app.py
    ports:
      - "5002:5000"
    depends_on:
      - db
    networks:
      - monitoring_net
    restart: always
    container_name: app2

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      SONAR_USER: sonarqube
      SONAR_PASSWORD: sonarqube
      SONAR_DB: sonarqube
      KONG_USER: kong
      KONG_PASSWORD: kong
      KONG_DB: kong
    ports:
      - "5432:5432"
    networks:
      - monitoring_net
    restart: always
    container_name: db
    volumes:
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh      

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - code_checker
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"      
    networks:
      - monitoring_net
    restart: always
    container_name: nginx


### Monitoring section
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    restart: always
    container_name: prometheus

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    networks:
      - monitoring_net
    command: -config.file=/etc/loki/local-config.yam
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    container_name: loki

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki    
    networks:
      - monitoring_net
    container_name: promtail

  grafana:
    image: grafana/grafana:10.1.10
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    restart: always
    container_name: grafana

  cadvisor:
    image: secureimages/cadvisor:0.47.2-alpine-3.18.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    privileged: true
    networks:
      - monitoring_net
    restart: always
    container_name: cadvisor

  node_exporter:
    image: prom/node-exporter:v1.8.0
    ports:
      - "9100:9100"
    networks:
      - monitoring_net
    restart: always
    container_name: node_exporter

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.25.0
    ports:
      - "9115:9115"
    networks:
      - monitoring_net
    container_name: blackbox_exporter


### API gateway
  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile.kong
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PG_DATABASE: kong
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    networks:
      - monitoring_net
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    container_name: kong

  konga:
    build:
      context: ./kong
      dockerfile: Dockerfile.konga
    depends_on:
      - kong
    environment:
      NODE_ENV: production
      KONGA_DB_ADAPTER: postgres
      KONGA_DB_URI: postgres://kong:kong@kong-db:5432/konga_db
      KONGA_HOOK_TIMEOUT: 120000
      TOKEN_SECRET: somerandomstring
    networks:
      - monitoring_net
    ports:
      - "1337:1337"
    container_name: konga


### Testing and validate our code
  code_checker:
    build:
      context: .
      dockerfile: code_checker/Dockerfile.pylint
    volumes:
      - ./app:/app
      - ./code_checker/.pylintrc:/app/.pylintrc
      - ./code_checker/test_script.sh:/app/test_script.sh      
    ports:
      - "5003:5000"
    networks:
      - monitoring_net
    container_name: code_checker
   
#  sonarqube:
#    build:
#      context: ./sonarqube
#      dockerfile: Dockerfile.sonarqube
#    ports:
#      - "9000:9000"
#    networks:
#      - monitoring_net
#    restart: always
#    volumes:
#      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
#      - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
#      - ./sonarqube/sonarqube_logs:/opt/sonarqube/logs
#      - $PWD/app:/mnt/code
#    environment:
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
#      - SONARQUBE_JDBC_USERNAME=sonarqube
#      - SONARQUBE_JDBC_PASSWORD=sonarqube
#    container_name: sonarqube
#
#  flake8_checker:
#    build:
#      context: .
#      dockerfile: code_checker/Dockerfile.flake8
#    volumes:
#      - ./app:/app
#    networks:
#      - monitoring_net
#    container_name: flake8_checker
#
#  wiremock:
#    build:
#      context: ./code_checker
#      dockerfile: Dockerfile.wiremock
#    volumes:
#      - ./code_checker/mappings:/home/wiremock/mappings
#      - ./code_checker/__files:/home/wiremock/__files
#    networks:
#      - monitoring_net
#    container_name: wiremock
#    ports:
#      - "8090:8090"


networks:
  monitoring_net:

