{
 "title": "Prometheus Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(prometheus_http_requests_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Status Code - App1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://app1:5000\", job=\"blackbox\"}",
     "legendFormat": "App1"
    }
   ]
  },
  {
   "title": "HTTP Duration - App1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"http://app1:5000\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Status Code - App2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"http://app2:5000\", job=\"blackbox\"}",
     "legendFormat": "App1"
    }
   ]
  },
  {
   "title": "HTTP Duration - App2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"http://app2:5000\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Version - App1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=\"http://app1:5000\"}"
    }
   ]
  },
  {
   "title": "HTTP Version - App2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=\"http://app2:5000\"}"
    }
   ]
  },
  {
   "title": "Average Probe Duration - App1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"http://app1:5000\"})"
    }
   ]
  },
  {
   "title": "Average Probe Duration - App2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"http://app2:5000\"})"
    }
   ]
  },
  {
   "title": "Probe Duration - App1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"http://app1:5000\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Probe Duration - App2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"http://app2:5000\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Average DNS Lookup - App1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=\"http://app1:5000\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup - App2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=\"http://app2:5000\"})"
    }
   ]
  },
  {
   "title": "SSL Expiry - App1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"http://app1:5000\"} - time()"
    }
   ]
  },
  {
   "title": "SSL Expiry - App2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"http://app2:5000\"} - time()"
    }
   ]
  },
  {
   "title": "SSL - App1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"http://app1:5000\"}"
    }
   ]
  },
  {
   "title": "SSL - App2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"http://app2:5000\"}"
    }
   ]
  }
 ]
}